# Generated by Django 4.2 on 2025-11-13 10:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, help_text='URL логотипа бренда', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(help_text='Производитель (Lamis, Caizer, Blesk, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.brand')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['section', 'brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('image', models.URLField(blank=True, help_text='URL изображения коллекции (картинка с R2)', max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(help_text='Производитель', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='products.brand')),
                ('category', models.ForeignKey(help_text='Категория товаров', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='products.category')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'db_table': 'collections',
                'ordering': ['brand', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'sections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='Категория товаров', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='products.category')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'db_table': 'types',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('main_image_url', models.URLField(max_length=500)),
                ('hover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('is_new', models.BooleanField(db_index=True, default=False)),
                ('is_on_sale', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='Производитель (обязательно)', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(help_text='Категория товаров', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('collection', models.ForeignKey(blank=True, help_text='Коллекция (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.collection')),
                ('section', models.ForeignKey(help_text='Раздел каталога', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.section')),
                ('type', models.ForeignKey(blank=True, help_text='Тип/Вид (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.type')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(help_text='Раздел каталога (Мебель для ванной, Санфарфор, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.section'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['section', 'brand'], name='products_section_f116c8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['section', 'brand', 'category'], name='products_section_deec61_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['section', 'brand', 'category', 'collection'], name='products_section_28f416_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['section', 'brand', 'category', 'type'], name='products_section_66a243_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new', 'is_on_sale'], name='products_is_new_f20030_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('section', 'brand', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('brand', 'category', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('section', 'brand', 'slug')},
        ),
    ]
