# Generated by Django 4.2 on 2025-11-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, help_text='SEO заголовок для описания раздела', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text='Описание раздела (2-3 параграфа)', null=True),
        ),
    ]
