# Generated by Django 4.2 on 2025-11-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_section_title_alter_section_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Установка мебели', max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Например: furniture-installation', max_length=250, unique=True, verbose_name='URL slug')),
                ('banner_image_url', models.URLField(help_text='Фоновое изображение для hero section', verbose_name='URL фото для hero section')),
                ('order', models.IntegerField(default=0, help_text='Меньшее число = выше в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать на фронтенде', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutorial Category',
                'verbose_name_plural': 'Tutorial Categories',
                'db_table': 'tutorial_categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Сборка шкафа-купе', max_length=200, verbose_name='Название видео')),
                ('youtube_video_id', models.CharField(help_text='ID видео на YouTube (например: dQw4w9WgXcQ)', max_length=20, verbose_name='YouTube Video ID')),
                ('order', models.IntegerField(default=0, help_text='Меньшее число = выше в списке', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.tutorialcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Tutorial Video',
                'verbose_name_plural': 'Tutorial Videos',
                'db_table': 'tutorial_videos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
