# Generated by Django 4.2 on 2025-11-15 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tutorialcategory_tutorialvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Например: Каталоги, Сертификаты, Логотипы', max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание категории материалов', null=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, help_text='Меньшее число = выше в списке', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material Category',
                'verbose_name_plural': 'Material Categories',
                'db_table': 'material_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Каталог продукции 2024', max_length=255, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, help_text='Подробное описание материала', null=True, verbose_name='Описание')),
                ('file_url', models.URLField(help_text='URL для скачивания файла (может быть внешняя ссылка или путь на сервере)', max_length=500, verbose_name='Ссылка на файл')),
                ('order', models.IntegerField(default=0, help_text='Меньшее число = выше в списке. Используется для ручной сортировки.', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отключите, если материал устарел и не должен показываться на сайте', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Категория материала', on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='products.materialcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': 'materials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_active', 'order'], name='materials_is_acti_503076_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['category', 'is_active'], name='materials_categor_54d61a_idx'),
        ),
    ]
