# Generated by Django 4.2 on 2025-11-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_materialcategory_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Например: Белый глянец, Дуб венге, Хром', max_length=100, unique=True, verbose_name='Название цвета')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='Код цвета в формате #FFFFFF (для простых цветов)', max_length=7, null=True, verbose_name='HEX код')),
                ('texture_image', models.URLField(blank=True, help_text='URL изображения текстуры (для материалов типа дерево, камень и т.д.)', max_length=500, null=True, verbose_name='URL текстуры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'colors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color_group',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID для связывания продуктов-вариаций одной модели. Продукты с одинаковым color_group являются цветовыми вариациями друг друга.', null=True, verbose_name='Группа цветовых вариаций'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text="DEPRECATED: Используйте поле 'color' и 'color_group' вместо этого", verbose_name='Цвета (устаревшее)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['color_group'], name='products_color_g_4fed88_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Цвет продукта из справочника', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.color', verbose_name='Цвет'),
        ),
    ]
