# Generated by Django 4.2 on 2025-11-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_color_product_color_group_alter_product_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Ссылка на изображение', max_length=500, verbose_name='URL изображения')),
                ('image_type', models.CharField(choices=[('main', 'Главное изображение'), ('hover', 'Изображение при наведении'), ('gallery', 'Галерея')], default='gallery', help_text='main - главное, hover - при наведении, gallery - дополнительные', max_length=10, verbose_name='Тип изображения')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Меньшее число = выше в списке', verbose_name='Порядок сортировки')),
                ('alt_text', models.CharField(blank=True, help_text='Альтернативный текст для SEO и доступности', max_length=255, null=True, verbose_name='Alt текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'db_table': 'product_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'image_type'], name='product_ima_product_7ecf37_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'sort_order'], name='product_ima_product_66d32e_idx'),
        ),
    ]
