# Generated by Django 4.2 on 2025-11-18 17:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, default=list, help_text='Структурированные характеристики товара в формате [{"key": "Ширина", "value": "60 см"}, ...]', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Полное описание товара с возможностью форматирования (жирный, курсив, списки и т.д.)', null=True, verbose_name='Описание товара'),
        ),
    ]
