# Generated by Django 4.2 on 2025-11-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_description_and_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/400x300?text=Material+Image', help_text='URL картинки для отображения материала', max_length=500, verbose_name='Ссылка на картинку'),
        ),
    ]
