# Generated by Django 4.2 on 2025-11-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_image_url_to_material'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='material',
            name='materials_categor_54d61a_idx',
        ),
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
    ]
