# Generated by Django 4.2 on 2025-11-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_category_from_material'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_new_f20030_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text="Отметьте, чтобы товар отображался в блоке 'Сантехника CAIZER' на главной странице", verbose_name='Показать на главной'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new', 'is_on_sale', 'is_featured'], name='products_is_new_20a812_idx'),
        ),
    ]
