# Generated by Claude Code

from django.db import migrations


def set_caizer_products_featured(apps, schema_editor):
    """
    Set is_featured=True for all CAIZER brand products.
    This makes them appear in the "Сантехника CAIZER" section on homepage.
    """
    Product = apps.get_model('products', 'Product')
    Brand = apps.get_model('products', 'Brand')

    # Find CAIZER brand
    try:
        caizer_brand = Brand.objects.get(name__icontains='Caizer')
        # Update all CAIZER products to be featured
        updated = Product.objects.filter(brand=caizer_brand).update(is_featured=True)
        print(f"\n✅ Set is_featured=True for {updated} CAIZER products")
    except Brand.DoesNotExist:
        print("\n⚠️ CAIZER brand not found, skipping featured products setup")
    except Exception as e:
        print(f"\n⚠️ Error setting featured products: {e}")


def unset_caizer_products_featured(apps, schema_editor):
    """
    Reverse: unset is_featured for all CAIZER products.
    """
    Product = apps.get_model('products', 'Product')
    Brand = apps.get_model('products', 'Brand')

    try:
        caizer_brand = Brand.objects.get(name__icontains='Caizer')
        Product.objects.filter(brand=caizer_brand).update(is_featured=False)
    except Brand.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_is_featured_field'),
    ]

    operations = [
        migrations.RunPython(
            set_caizer_products_featured,
            unset_caizer_products_featured
        ),
    ]
