# Generated by Django 4.2 on 2025-11-29 10:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_set_caizer_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='material',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='URL картинки для отображения материала', max_length=500, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(help_text='Производитель (обязательно)', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Категория товаров', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Коллекция (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(help_text='Раздел каталога', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Тип/Вид (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
