# Generated by Django 4.2 on 2025-11-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='partners_logos/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Наши клиенты',
            },
        ),
    ]
